version: '3.8'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/server/
    environment:
      - PORT=9080
    ports:
      - 9080:9080
    restart: on-failure
    volumes:
      - server_vol:/usr/src/server/
    networks:
      - monorepo_net

  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/client/
    environment:
      - SERVER_ADDRESS=server:9080
    depends_on:
      - server
    restart: on-failure
    volumes:
      - client_vol:/usr/src/client/
    networks:
      - monorepo_net

volumes:
  server_vol:
  client_vol:

networks:
  monorepo_net:
    driver: bridge
